[package]
name = "revm-jit"
description = "Revm JIT backend"
homepage = "https://github.com/danipopes/revm-jit/tree/main/crates/revm-jit"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
revm-jit-core.workspace = true

revm-jit-llvm = { workspace = true, optional = true }
revm-jit-cranelift = { workspace = true, optional = true }

revm-primitives.workspace = true
revm-interpreter.workspace = true
color-eyre.workspace = true

[features]
default = ["llvm"]
llvm = ["dep:revm-jit-llvm"]
cranelift = ["dep:revm-jit-cranelift"]

[[bin]]
name = "revm-jit"
path = "src/main.rs"
required-features = ["llvm"]
doc = false
