[package]
name = "revm-jit"
description = "Revm JIT backend"
homepage = "https://github.com/danipopes/revm-jit/tree/main/crates/cranelift-jit-evm"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
