[workspace]
members = ["crates/*"]
# exclude cranelift as it doesn't work yet
default-members = ["crates/revm-jit", "crates/revm-jit-backend", "crates/revm-jit-llvm"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["DaniPopes <57450786+DaniPopes@users.noreply.github.com>"]
edition = "2021"
rust-version = "1.77"
license = "MIT OR Apache-2.0"
categories = ["compilers", "cryptography::cryptocurrencies"]
keywords = ["compile", "compiler", "jit", "evm", "ethereum"]
homepage = "https://github.com/danipopes/cranelift-jit-evm"
repository = "https://github.com/danipopes/cranelift-jit-evm"
exclude = [".github/", "benches/", "fuzz/", "tests/"]

[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"
rustdoc.all = "warn"

[workspace.dependencies]
revm-jit = { version = "0.1.0", path = "crates/revm-jit", default-features = false }
revm-jit-backend = { version = "0.1.0", path = "crates/revm-jit-backend", default-features = false }
revm-jit-cranelift = { version = "0.1.0", path = "crates/revm-jit-cranelift", default-features = false }
revm-jit-llvm = { version = "0.1.0", path = "crates/revm-jit-llvm", default-features = false }

alloy-primitives = "0.6"
revm-primitives = "3.1.0"
revm-interpreter = "3.4.0"
ruint = "1.12"

eyre = "0.6"
color-eyre = "0.6"
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = "0.3"

[patch.crates-io]
revm-primitives = { git = "https://github.com/bluealloy/revm" }
revm-interpreter = { git = "https://github.com/bluealloy/revm" }
